public class Instructions
{
    public static readonly Dictionary<string, byte> Operators = new()
    {
        ["PRC"] = 1,
        ["PBC"] = 2,
        ["PHC"] = 3,
        ["PDC"] = 4,
        ["PSC"] = 5,
        ["PCC"] = 6,
        ["JIF"] = 10,
        ["JNF"] = 11,
        ["LDA"] = 64,
        ["STA"] = 65,
        ["ATA"] = 66,
        ["SFA"] = 67,
        ["MBA"] = 68,
        ["DBA"] = 69,
        ["MOA"] = 70,
        ["FAE"] = 71,
        ["FAM"] = 72,
        ["FAL"] = 73,
        ["LDB"] = 80,
        ["STB"] = 81,
        ["ATB"] = 82,
        ["SFB"] = 83,
        ["MBB"] = 84,
        ["DBB"] = 85,
        ["MOB"] = 86,
        ["FBE"] = 87,
        ["FBM"] = 88,
        ["FBL"] = 89,
    };
    public static readonly Dictionary<string, byte> SubOperators = new()
    {
        ["MIN"] = 0,
        ["MAX"] = 1,
        ["ARB"] = 2,
        ["ARG"] = 4,
        ["BRG"] = 5,
        ["ACC"] = 6,
        ["XRG"] = 7,
        ["YRG"] = 8,
        ["STK"] = 9,
        ["CRM"] = 10,
        ["WRM"] = 11,
    };
    public static readonly Dictionary<byte, string> ReverseOperators = new()
    {
        [1] = "PRC",
        [2] = "PBC",
        [3] = "PHC",
        [4] = "PDC",
        [5] = "PSC",
        [6] = "PCC",
        [10] = "JIF",
        [11] = "JNF",
        [64] = "LDA",
        [65] = "STA",
        [66] = "ATA",
        [67] = "SFA",
        [68] = "MBA",
        [69] = "DBA",
        [70] = "MOA",
        [71] = "FAE",
        [72] = "FAM",
        [73] = "FAL",
        [80] = "LDB",
        [81] = "STB",
        [82] = "ATB",
        [83] = "SFB",
        [84] = "MBB",
        [85] = "DBB",
        [86] = "MOB",
        [87] = "FBE",
        [88] = "FBM",
        [89] = "FBL",
    };
    public static readonly Dictionary<byte, string> ReverseSubOperators = new()
    {
        [0] = "MIN",
        [1] = "MAX",
        [2] = "ARB",
        [4] = "ARG",
        [5] = "BRG",
        [6] = "ACC",
        [7] = "XRG",
        [8] = "YRG",
        [9] = "STK",
        [10] = "CRM",
        [11] = "WRM",
    };

}